[package]
name = "ctp"
version = "0.1.3"
edition = "2021"
description = "Create The Project"
license = "MIT"
authors = ["William Lane <williamlane923@gmail.com>"]
repository = "https://github.com/willdoescode/ctp"

[dependencies]
anyhow = "1.0.44"
clap = { version = "4.3.19", features = ["derive"] }
thiserror = "1.0.30"
toml = "0.5.8"
